name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "693c8128b82b4434ad8259f481768707" },
  { binding = "SHARE", id = "b38ac3d24ae248a8a1dc734285a6ec20" }
]